<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('purchase_orders', function (Blueprint $table) {
            $table->id();
            $table->string('po_number')->unique();
            $table->foreignId('supplier_id')->constrained()->restrictOnDelete();
            $table->foreignId('location_id')->constrained()->restrictOnDelete(); // Delivery destination

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); // The user or 'null' for automated AI POs
            $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();

            $table->string('status')->default('draft'); // 'draft', 'pending_approval', 'approved', 'sent', 'partially_received', 'fulfilled', 'cancelled'

            // Financials
            $table->decimal('subtotal', 12, 2)->default(0);
            $table->decimal('tax_amount', 12, 2)->default(0);
            $table->decimal('total_amount', 12, 2)->default(0);
            $table->string('currency')->default('USD');

            // Automation Details
            $table->boolean('is_automated')->default(false); // Flag if generated by CheckLowStockJob
            $table->text('notes')->nullable();

            $table->timestamp('expected_delivery_date')->nullable();
            $table->timestamp('approved_at')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
            $table->index('po_number');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('purchase_orders');
    }
};
